FROM maven:3.9.6-eclipse-temurin-21

WORKDIR /app

# Copy toàn bộ source vào container
COPY . .

# Build (skip tests)
RUN chmod +x mvnw && ./mvnw clean package -DskipTests

# Thiết lập biến môi trường mặc định
ENV JAVA_OPTS="-Xms256m -Xmx512m" \
    TZ=Asia/Ho_Chi_Minh

# Expose port
EXPOSE 8080

# Entrypoint chạy ứng dụng
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar target/*.jar"]