--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-08-06 11:33:00

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 4 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA IF NOT EXISTS public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- TOC entry 5083 (class 0 OID 0)
-- Dependencies: 4
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 197415)
-- Name: account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.account (
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    linked_id bigint,
    updated_at timestamp(6) without time zone,
    avatar_url character varying(255),
    password character varying(255),
    username character varying(255) NOT NULL,
    roles smallint[]
);


ALTER TABLE public.account OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 197414)
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 197425)
-- Name: class_section; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.class_section (
    end_date date,
    start_date date,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    semester_id bigint,
    subject_id bigint,
    teacher_id bigint,
    updated_at timestamp(6) without time zone,
    name character varying(255)
);


ALTER TABLE public.class_section OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 197424)
-- Name: class_section_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.class_section ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 197431)
-- Name: enrollment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.enrollment (
    status smallint,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    section_id bigint,
    student_id bigint,
    updated_at timestamp(6) without time zone,
    CONSTRAINT enrollment_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.enrollment OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 197430)
-- Name: enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.enrollment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 197438)
-- Name: faculty; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.faculty (
    dean_id bigint,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(255)
);


ALTER TABLE public.faculty OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 197437)
-- Name: faculty_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.faculty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.faculty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
--
-- TOC entry 227 (class 1259 OID 197446)
-- Name: major; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.major (
    deleted_at timestamp(6) without time zone,
    faculty_id bigint,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(255)
);


ALTER TABLE public.major OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 197445)
-- Name: major_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.major ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.major_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 197452)
-- Name: payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payment (
    payment_date date,
    payment_method smallint,
    amount_paid bigint,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    tuition_id bigint,
    updated_at timestamp(6) without time zone,
    note character varying(255),
    reference_number character varying(255),
    CONSTRAINT payment_payment_method_check CHECK (((payment_method >= 0) AND (payment_method <= 1)))
);


ALTER TABLE public.payment OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 197451)
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 197461)
-- Name: prerequisite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.prerequisite (
    pass_requirement boolean NOT NULL,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    prerequisite_id bigint,
    subject_id bigint,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.prerequisite OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 197460)
-- Name: prerequisite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.prerequisite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prerequisite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 197467)
-- Name: program; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.program (
    duration integer,
    level smallint,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    major_id bigint,
    updated_at timestamp(6) without time zone,
    name character varying(255),
    CONSTRAINT program_level_check CHECK (((level >= 0) AND (level <= 2)))
);


ALTER TABLE public.program OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 197466)
-- Name: program_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.program ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.program_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 197474)
-- Name: schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schedule (
    end_period integer NOT NULL,
    start_period integer NOT NULL,
    week_day smallint,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    section_id bigint,
    updated_at timestamp(6) without time zone,
    room character varying(255),
    CONSTRAINT schedule_week_day_check CHECK (((week_day >= 0) AND (week_day <= 5)))
);


ALTER TABLE public.schedule OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 197473)
-- Name: schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 197481)
-- Name: score; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.score (
    final_score real,
    mid_term_score real,
    process_score real,
    deleted_at timestamp(6) without time zone,
    enrollment_id bigint,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.score OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 197480)
-- Name: score_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 239 (class 1259 OID 197489)
-- Name: semester; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.semester (
    end_date date,
    start_date date,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(255)
);


ALTER TABLE public.semester OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 197488)
-- Name: semester_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.semester ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.semester_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 241 (class 1259 OID 197495)
-- Name: student; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student (
    dob date,
    entry_date date,
    gender smallint,
    status smallint,
    class_id bigint,
    deleted_at timestamp(6) without time zone,
    fee_id bigint,
    id bigint NOT NULL,
    major_id bigint,
    updated_at timestamp(6) without time zone,
    address character varying(255),
    email character varying(255),
    name character varying(255),
    phone character varying(255),
    CONSTRAINT student_gender_check CHECK (((gender >= 0) AND (gender <= 1))),
    CONSTRAINT student_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.student OWNER TO postgres;

--
-- TOC entry 243 (class 1259 OID 197505)
-- Name: student_class; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.student_class (
    end_year integer,
    start_year integer,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    name character varying(255)
);


ALTER TABLE public.student_class OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 197504)
-- Name: student_class_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 197494)
-- Name: student_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.student ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 197511)
-- Name: subject; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.subject (
    credits integer NOT NULL,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    major_id bigint,
    updated_at timestamp(6) without time zone,
    description character varying(255),
    name character varying(255),
    subject_code character varying(255)
);


ALTER TABLE public.subject OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 197510)
-- Name: subject_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 197519)
-- Name: teacher; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teacher (
    dob date,
    hire_date date,
    deleted_at timestamp(6) without time zone,
    faculty_id bigint,
    id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    degree character varying(255),
    email character varying(255),
    name character varying(255),
    phone character varying(255),
    specialization character varying(255)
);


ALTER TABLE public.teacher OWNER TO postgres;

--
-- TOC entry 246 (class 1259 OID 197518)
-- Name: teacher_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teacher ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 197527)
-- Name: tuition; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tuition (
    status smallint,
    deleted_at timestamp(6) without time zone,
    id bigint NOT NULL,
    remaining_amount bigint,
    semester_id bigint,
    student_id bigint,
    total_amount bigint,
    updated_at timestamp(6) without time zone,
    CONSTRAINT tuition_status_check CHECK (((status >= 0) AND (status <= 2)))
);


ALTER TABLE public.tuition OWNER TO postgres;

--
-- TOC entry 251 (class 1259 OID 197534)
-- Name: tuition_fee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tuition_fee (
    academic_year integer,
    effective_date date,
    expiry_date date,
    credit_fee bigint,
    deleted_at timestamp(6) without time zone,
    fixed_fee bigint,
    id bigint NOT NULL,
    program_id bigint,
    updated_at timestamp(6) without time zone
);


ALTER TABLE public.tuition_fee OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 197533)
-- Name: tuition_fee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tuition_fee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tuition_fee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 248 (class 1259 OID 197526)
-- Name: tuition_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tuition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tuition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5045 (class 0 OID 197415)
-- Dependencies: 219
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.account (deleted_at, id, linked_id, updated_at, avatar_url, password, username, roles) FROM stdin;
\N	1	\N	\N	\N	$2a$10$IPD0zC9ZfJOY39HtoY9wleiNctvqi97HETbmDWbGxjdTF0MZyxukW	user01	{2,1,0}
\.


--
-- TOC entry 5047 (class 0 OID 197425)
-- Dependencies: 221
-- Data for Name: class_section; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.class_section (end_date, start_date, deleted_at, id, semester_id, subject_id, teacher_id, updated_at, name) FROM stdin;
\.


--
-- TOC entry 5049 (class 0 OID 197431)
-- Dependencies: 223
-- Data for Name: enrollment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.enrollment (status, deleted_at, id, section_id, student_id, updated_at) FROM stdin;
\.


--
-- TOC entry 5051 (class 0 OID 197438)
-- Dependencies: 225
-- Data for Name: faculty; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.faculty (dean_id, deleted_at, id, updated_at, name) FROM stdin;
\.


--
-- TOC entry 5053 (class 0 OID 197446)
-- Dependencies: 227
-- Data for Name: major; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.major (deleted_at, faculty_id, id, updated_at, name) FROM stdin;
\.


--
-- TOC entry 5055 (class 0 OID 197452)
-- Dependencies: 229
-- Data for Name: payment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.payment (payment_date, payment_method, amount_paid, deleted_at, id, tuition_id, updated_at, note, reference_number) FROM stdin;
\.


--
-- TOC entry 5057 (class 0 OID 197461)
-- Dependencies: 231
-- Data for Name: prerequisite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.prerequisite (pass_requirement, deleted_at, id, prerequisite_id, subject_id, updated_at) FROM stdin;
\.


--
-- TOC entry 5059 (class 0 OID 197467)
-- Dependencies: 233
-- Data for Name: program; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.program (duration, level, deleted_at, id, major_id, updated_at, name) FROM stdin;
\.


--
-- TOC entry 5061 (class 0 OID 197474)
-- Dependencies: 235
-- Data for Name: schedule; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.schedule (end_period, start_period, week_day, deleted_at, id, section_id, updated_at, room) FROM stdin;
\.


--
-- TOC entry 5063 (class 0 OID 197481)
-- Dependencies: 237
-- Data for Name: score; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.score (final_score, mid_term_score, process_score, deleted_at, enrollment_id, id, updated_at) FROM stdin;
\.


--
-- TOC entry 5065 (class 0 OID 197489)
-- Dependencies: 239
-- Data for Name: semester; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.semester (end_date, start_date, deleted_at, id, updated_at, name) FROM stdin;
\.


--
-- TOC entry 5067 (class 0 OID 197495)
-- Dependencies: 241
-- Data for Name: student; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student (dob, entry_date, gender, status, class_id, deleted_at, fee_id, id, major_id, updated_at, address, email, name, phone) FROM stdin;
\.


--
-- TOC entry 5069 (class 0 OID 197505)
-- Dependencies: 243
-- Data for Name: student_class; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.student_class (end_year, start_year, deleted_at, id, updated_at, name) FROM stdin;
\.


--
-- TOC entry 5071 (class 0 OID 197511)
-- Dependencies: 245
-- Data for Name: subject; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.subject (credits, deleted_at, id, major_id, updated_at, description, name, subject_code) FROM stdin;
\.


--
-- TOC entry 5073 (class 0 OID 197519)
-- Dependencies: 247
-- Data for Name: teacher; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.teacher (dob, hire_date, deleted_at, faculty_id, id, updated_at, degree, email, name, phone, specialization) FROM stdin;
\.


--
-- TOC entry 5075 (class 0 OID 197527)
-- Dependencies: 249
-- Data for Name: tuition; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tuition (status, deleted_at, id, remaining_amount, semester_id, student_id, total_amount, updated_at) FROM stdin;
\.


--
-- TOC entry 5077 (class 0 OID 197534)
-- Dependencies: 251
-- Data for Name: tuition_fee; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tuition_fee (academic_year, effective_date, expiry_date, credit_fee, deleted_at, fixed_fee, id, program_id, updated_at) FROM stdin;
\.


--
-- TOC entry 5084 (class 0 OID 0)
-- Dependencies: 218
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.account_id_seq', 1, true);


--
-- TOC entry 5085 (class 0 OID 0)
-- Dependencies: 220
-- Name: class_section_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.class_section_id_seq', 1, false);


--
-- TOC entry 5086 (class 0 OID 0)
-- Dependencies: 222
-- Name: enrollment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.enrollment_id_seq', 1, false);


--
-- TOC entry 5087 (class 0 OID 0)
-- Dependencies: 224
-- Name: faculty_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.faculty_id_seq', 1, false);


--
-- TOC entry 5088 (class 0 OID 0)
-- Dependencies: 226
-- Name: major_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.major_id_seq', 1, false);


--
-- TOC entry 5089 (class 0 OID 0)
-- Dependencies: 228
-- Name: payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.payment_id_seq', 1, false);


--
-- TOC entry 5090 (class 0 OID 0)
-- Dependencies: 230
-- Name: prerequisite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.prerequisite_id_seq', 1, false);


--
-- TOC entry 5091 (class 0 OID 0)
-- Dependencies: 232
-- Name: program_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.program_id_seq', 1, false);


--
-- TOC entry 5092 (class 0 OID 0)
-- Dependencies: 234
-- Name: schedule_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.schedule_id_seq', 1, false);


--
-- TOC entry 5093 (class 0 OID 0)
-- Dependencies: 236
-- Name: score_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.score_id_seq', 1, false);


--
-- TOC entry 5094 (class 0 OID 0)
-- Dependencies: 238
-- Name: semester_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.semester_id_seq', 1, false);


--
-- TOC entry 5095 (class 0 OID 0)
-- Dependencies: 242
-- Name: student_class_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_class_id_seq', 1, false);


--
-- TOC entry 5096 (class 0 OID 0)
-- Dependencies: 240
-- Name: student_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.student_id_seq', 1, false);


--
-- TOC entry 5097 (class 0 OID 0)
-- Dependencies: 244
-- Name: subject_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.subject_id_seq', 1, false);


--
-- TOC entry 5098 (class 0 OID 0)
-- Dependencies: 246
-- Name: teacher_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teacher_id_seq', 1, false);


--
-- TOC entry 5099 (class 0 OID 0)
-- Dependencies: 250
-- Name: tuition_fee_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tuition_fee_id_seq', 1, false);


--
-- TOC entry 5100 (class 0 OID 0)
-- Dependencies: 248
-- Name: tuition_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tuition_id_seq', 1, false);


--
-- TOC entry 4838 (class 2606 OID 197421)
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- TOC entry 4840 (class 2606 OID 197423)
-- Name: account account_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_username_key UNIQUE (username);


--
-- TOC entry 4842 (class 2606 OID 197429)
-- Name: class_section class_section_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class_section
    ADD CONSTRAINT class_section_pkey PRIMARY KEY (id);


--
-- TOC entry 4844 (class 2606 OID 197436)
-- Name: enrollment enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollment
    ADD CONSTRAINT enrollment_pkey PRIMARY KEY (id);


--
-- TOC entry 4846 (class 2606 OID 197444)
-- Name: faculty faculty_dean_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT faculty_dean_id_key UNIQUE (dean_id);


--
-- TOC entry 4848 (class 2606 OID 197442)
-- Name: faculty faculty_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT faculty_pkey PRIMARY KEY (id);




--
-- TOC entry 4850 (class 2606 OID 197450)
-- Name: major major_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.major
    ADD CONSTRAINT major_pkey PRIMARY KEY (id);


--
-- TOC entry 4852 (class 2606 OID 197459)
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- TOC entry 4854 (class 2606 OID 197465)
-- Name: prerequisite prerequisite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prerequisite
    ADD CONSTRAINT prerequisite_pkey PRIMARY KEY (id);


--
-- TOC entry 4856 (class 2606 OID 197472)
-- Name: program program_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT program_pkey PRIMARY KEY (id);


--
-- TOC entry 4858 (class 2606 OID 197479)
-- Name: schedule schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedule
    ADD CONSTRAINT schedule_pkey PRIMARY KEY (id);


--
-- TOC entry 4860 (class 2606 OID 197487)
-- Name: score score_enrollment_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.score
    ADD CONSTRAINT score_enrollment_id_key UNIQUE (enrollment_id);


--
-- TOC entry 4862 (class 2606 OID 197485)
-- Name: score score_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.score
    ADD CONSTRAINT score_pkey PRIMARY KEY (id);


--
-- TOC entry 4864 (class 2606 OID 197493)
-- Name: semester semester_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.semester
    ADD CONSTRAINT semester_pkey PRIMARY KEY (id);


--
-- TOC entry 4868 (class 2606 OID 197509)
-- Name: student_class student_class_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student_class
    ADD CONSTRAINT student_class_pkey PRIMARY KEY (id);


--
-- TOC entry 4866 (class 2606 OID 197503)
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (id);


--
-- TOC entry 4870 (class 2606 OID 197517)
-- Name: subject subject_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT subject_pkey PRIMARY KEY (id);


--
-- TOC entry 4872 (class 2606 OID 197525)
-- Name: teacher teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (id);


--
-- TOC entry 4876 (class 2606 OID 197538)
-- Name: tuition_fee tuition_fee_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tuition_fee
    ADD CONSTRAINT tuition_fee_pkey PRIMARY KEY (id);


--
-- TOC entry 4874 (class 2606 OID 197532)
-- Name: tuition tuition_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tuition
    ADD CONSTRAINT tuition_pkey PRIMARY KEY (id);


--
-- TOC entry 4877 (class 2606 OID 197539)
-- Name: class_section fk12ff0gutbooglku3rnsjvsb2t; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class_section
    ADD CONSTRAINT fk12ff0gutbooglku3rnsjvsb2t FOREIGN KEY (semester_id) REFERENCES public.semester(id);


--
-- TOC entry 4890 (class 2606 OID 197609)
-- Name: student fk6jmw3w31l9ojcckkrgv3ga7un; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fk6jmw3w31l9ojcckkrgv3ga7un FOREIGN KEY (class_id) REFERENCES public.student_class(id);


--
-- TOC entry 4891 (class 2606 OID 197604)
-- Name: student fkcml1vvjs3bcqyxdcprjrjd2o0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkcml1vvjs3bcqyxdcprjrjd2o0 FOREIGN KEY (major_id) REFERENCES public.major(id);


--
-- TOC entry 4892 (class 2606 OID 197614)
-- Name: student fkdeqcu776u8v5balguywtydws8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT fkdeqcu776u8v5balguywtydws8 FOREIGN KEY (fee_id) REFERENCES public.tuition_fee(id);


--
-- TOC entry 4897 (class 2606 OID 197639)
-- Name: tuition_fee fkfwtre4gwo4cxyii7h9ui8dn6l; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tuition_fee
    ADD CONSTRAINT fkfwtre4gwo4cxyii7h9ui8dn6l FOREIGN KEY (program_id) REFERENCES public.program(id);


--
-- TOC entry 4887 (class 2606 OID 197589)
-- Name: program fkgeqdku3wynlk0n2jbmss3kk8q; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.program
    ADD CONSTRAINT fkgeqdku3wynlk0n2jbmss3kk8q FOREIGN KEY (major_id) REFERENCES public.major(id);


--
-- TOC entry 4889 (class 2606 OID 197599)
-- Name: score fkgnvnqbenjt1kh0xn9h8h75xqn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.score
    ADD CONSTRAINT fkgnvnqbenjt1kh0xn9h8h75xqn FOREIGN KEY (enrollment_id) REFERENCES public.enrollment(id);


--
-- TOC entry 4882 (class 2606 OID 197564)
-- Name: faculty fki452shko2tqbjeak0fxfhpl59; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.faculty
    ADD CONSTRAINT fki452shko2tqbjeak0fxfhpl59 FOREIGN KEY (dean_id) REFERENCES public.teacher(id);


--
-- TOC entry 4880 (class 2606 OID 197559)
-- Name: enrollment fkio7fsy3vhvfgv7c0gjk15nyk4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollment
    ADD CONSTRAINT fkio7fsy3vhvfgv7c0gjk15nyk4 FOREIGN KEY (student_id) REFERENCES public.student(id);


--
-- TOC entry 4881 (class 2606 OID 197554)
-- Name: enrollment fkkjesxtln74fkse2ao7hoifmh1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.enrollment
    ADD CONSTRAINT fkkjesxtln74fkse2ao7hoifmh1 FOREIGN KEY (section_id) REFERENCES public.class_section(id);


--
-- TOC entry 4884 (class 2606 OID 197574)
-- Name: payment fkm3d37ueh7laaofh1fkr1t4wp3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT fkm3d37ueh7laaofh1fkr1t4wp3 FOREIGN KEY (tuition_id) REFERENCES public.tuition(id);


--
-- TOC entry 4895 (class 2606 OID 197634)
-- Name: tuition fkmw01a1icmtp696yk6tcruqwce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tuition
    ADD CONSTRAINT fkmw01a1icmtp696yk6tcruqwce FOREIGN KEY (student_id) REFERENCES public.student(id);


--
-- TOC entry 4878 (class 2606 OID 197544)
-- Name: class_section fknk6p5i4iend937wessbb5vvyj; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class_section
    ADD CONSTRAINT fknk6p5i4iend937wessbb5vvyj FOREIGN KEY (subject_id) REFERENCES public.subject(id);


--
-- TOC entry 4896 (class 2606 OID 197629)
-- Name: tuition fko30ab1uspy4xvq6l10jypqqev; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tuition
    ADD CONSTRAINT fko30ab1uspy4xvq6l10jypqqev FOREIGN KEY (semester_id) REFERENCES public.semester(id);


--
-- TOC entry 4885 (class 2606 OID 197579)
-- Name: prerequisite fkonespnj414epm6b9kxa8gaup5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prerequisite
    ADD CONSTRAINT fkonespnj414epm6b9kxa8gaup5 FOREIGN KEY (prerequisite_id) REFERENCES public.subject(id);


--
-- TOC entry 4886 (class 2606 OID 197584)
-- Name: prerequisite fkp4w8gsokcyq3m0xkif7fxec6h; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.prerequisite
    ADD CONSTRAINT fkp4w8gsokcyq3m0xkif7fxec6h FOREIGN KEY (subject_id) REFERENCES public.subject(id);


--
-- TOC entry 4893 (class 2606 OID 197619)
-- Name: subject fkpjawa5kgl1xt4bhrbladxcf9i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.subject
    ADD CONSTRAINT fkpjawa5kgl1xt4bhrbladxcf9i FOREIGN KEY (major_id) REFERENCES public.major(id);


--
-- TOC entry 4894 (class 2606 OID 197624)
-- Name: teacher fkqbtffr96yb132f3vi87okefkh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT fkqbtffr96yb132f3vi87okefkh FOREIGN KEY (faculty_id) REFERENCES public.faculty(id);


--
-- TOC entry 4888 (class 2606 OID 197594)
-- Name: schedule fkqcrwbhe9nnomlap870mocjko; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedule
    ADD CONSTRAINT fkqcrwbhe9nnomlap870mocjko FOREIGN KEY (section_id) REFERENCES public.class_section(id);


--
-- TOC entry 4879 (class 2606 OID 197549)
-- Name: class_section fkqcswn3cikhqy5627i3rj2ik0u; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.class_section
    ADD CONSTRAINT fkqcswn3cikhqy5627i3rj2ik0u FOREIGN KEY (teacher_id) REFERENCES public.teacher(id);


--
-- TOC entry 4883 (class 2606 OID 197569)
-- Name: major fkrbpflj1p41y81s9d2jf5ix2jv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.major
    ADD CONSTRAINT fkrbpflj1p41y81s9d2jf5ix2jv FOREIGN KEY (faculty_id) REFERENCES public.faculty(id);


-- Completed on 2025-08-06 11:33:01

--
-- PostgreSQL database dump complete
--

