name: Build and push to Docker Hub

on:
#  push:
#    branches:
#      - master
#  pull_request:
#    branches:
#      - master
    workflow_dispatch:
      inputs:
        release:
          description: 'Release version'
          required: true
          default: '1.0.0'
        run_cd:
          description: 'Trigger CD after build?'
          required: false
          type: choice
          default: 'false'
          options:
            - 'true'
            - 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project
        run: mvn clean package -DskipTests

      - name: Copy project dependencies ( used for SonarCloud Scan )
        run: mvn dependency:copy-dependencies

      - name: Trivy File Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: .
          format: 'template'
          template: "@$HOME/.local/bin/trivy-bin/contrib/html.tpl"
          output: 'fs.html'
          skip-dirs: target,.git

      - name: Upload File Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: fs-scan-report
          path: fs.html

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    name: Build, Scan & Push Docker image
    runs-on: ubuntu-latest
    needs: build
    env:
      IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.IMAGE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Multi-Arch Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ github.event.inputs.release }}-${{ github.run_number }}
          cache-from: type=registry,ref=${{ env.IMAGE }}-buildcache
          cache-to: type=registry,ref=${{ env.IMAGE }}-buildcache,mode=max
          provenance: false
          sbom: false

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}
          format: 'template'
          template: "@$HOME/.local/bin/trivy-bin/contrib/html.tpl"
          output: 'trivy-image-report.html'

      - name: Upload Trivy Image Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-image-report
          path: trivy-image-report.html
